# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'BaseProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaseProject
pod 'Alamofire', '~>4.7'
pod 'SwiftyJSON'
pod 'SwiftLint'
pod 'ReachabilitySwift'

end
